//@flow
import moment from 'moment';

import type { postType } from '../flow/exports';

export const dummyPosts: Array<postType> = [
  {
    id: 1,
    username: 'John15',
    postTitle: 'Hello World',
    views: 15,
    likes: 90,
    createdAt: moment('11-05-2019', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 2,
    username: 'Mary',
    postTitle: 'World',
    views: 5,
    likes: 30,
    createdAt: moment('10-05-2019', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 3,
    username: 'Bob',
    postTitle: 'zzzz',
    views: 10,
    likes: 20,
    createdAt: moment('12-05-2019', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 4,
    username: 'Adela',
    postTitle: 'zzzz',
    views: 10,
    likes: 20,
    createdAt: moment('12-05-2019', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 5,
    username: 'Nazair',
    postTitle: 'zzzz',
    views: 10,
    likes: 20,
    createdAt: moment('12-05-2019', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 6,
    username: 'Yeti',
    postTitle: 'zzzz',
    views: 10,
    likes: 20,
    createdAt: moment('12-05-2019', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 7,
    username: 'Bob',
    postTitle: 'zzzz',
    views: 10,
    likes: 20,
    createdAt: moment('12-05-2019', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 8,
    username: 'Bob',
    postTitle: 'zzzz',
    views: 10,
    likes: 20,
    createdAt: moment('12-05-2019', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 9,
    username: 'Bob',
    postTitle: 'zzzz',
    views: 10,
    likes: 20,
    createdAt: moment('12-05-2019', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 10,
    username: 'Bob',
    postTitle: 'zzzz',
    views: 10,
    likes: 20,
    createdAt: moment('12-05-2019', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 11,
    username: 'Bob',
    postTitle: 'zzzz',
    views: 10,
    likes: 20,
    createdAt: moment('12-05-2019', 'MM-DD-YYYY').valueOf(),
  },
];
