//@flow
import moment from 'moment';

import type { postType } from '../flow/exports';

export const dummyPosts: Array<postType> = [
  {
    id: 1,
    username: 'John15',
    postTitle: 'Hello World everyone!',
    views: 15,
    likes: 90,
    createdAt: moment('12-05-2018', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 2,
    username: 'Mary',
    postTitle: 'World at fire',
    views: 5,
    likes: 30,
    createdAt: moment('12-05-2018', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 3,
    username: 'Bob',
    postTitle: 'Funky fouls',
    views: 10,
    likes: 20,
    createdAt: moment('12-02-2018', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 4,
    username: 'Adela',
    postTitle: 'Freaky friday',
    views: 10,
    likes: 30,
    createdAt: moment('12-01-2018', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 5,
    username: 'Jazz',
    postTitle: 'Jackrabbit is the best',
    views: 10,
    likes: 10,
    createdAt: moment('12-05-2018', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 6,
    username: 'Yeti',
    postTitle: 'snowing in the mountains',
    views: 20,
    likes: 1,
    createdAt: moment('12-01-2018', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 7,
    username: 'Joel',
    postTitle: 'I hate Alaska, or am I?>',
    views: 2,
    likes: 4,
    createdAt: moment('12-03-2018', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 8,
    username: 'Beatrice',
    postTitle: 'Ulysess...',
    views: 23,
    likes: 234,
    createdAt: moment('12-03-2018', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 9,
    username: 'Some dude',
    postTitle: ' whats up!',
    views: 144,
    likes: 0,
    createdAt: moment('12-03-2018', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 10,
    username: 'Bobby',
    postTitle: 'I swear I can not go',
    views: 10,
    likes: 0,
    createdAt: moment('12-08-2018', 'MM-DD-YYYY').valueOf(),
  },
  {
    id: 11,
    username: 'Mummy',
    postTitle: 'Model mommy or model mummy?',
    views: 10,
    likes: 20,
    createdAt: moment('12-07-2018', 'MM-DD-YYYY').valueOf(),
  },
];
